apiVersion: v1
kind: Service
metadata:
  name: contoso-website
spec:
  selector:
    app: contoso-website
  type: LoadBalancer
  ports:
    - name: react-port
      port: 80
      targetPort: 3000
    - name: api-port
      port: 4000
      targetPort: 4000