apiVersion: v1
kind: Service
metadata:
  name: contoso-website
spec:
  selector:
    app: contoso-website
  type: LoadBalancer
  ports:
    - name: react-port
      port: 3000 #this is port of the host
      targetPort: 3000  #this is port of container
    - name: api-port
      port: 4000
      targetPort: 4000